apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nfs-pvc
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/media/nfs/k8spvc"
    # persistentVolumeReclaimPolicy: Retain
  #  local:
          #    path: /media/nfs/k8spvc/
