apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  externalIPs:
  - 10.168.57.253
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: grafana
